spring.datasource.url=jdbc:postgresql://localhost:5433/gym
spring.datasource.username=admin
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=gym

logging.level.org.springframework.jdbc.core=DEBUG